# Topic: Decision Tree & Random Forest
# Name: R.Ramakrishna Raju
# Batch: 09012021

Problem Statement: -
 Divide the data (Diabetes) into training and test datasets and create a Random Forest and Decision Tree Model to classify 'Class Variable' or “Outcome” 


# Importing Dataset


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv(r"F:\360\DT\Diabetes.csv")
df

Number of times pregnant   Plasma glucose concentration  \
0                            6                            148   
1                            1                             85   
2                            8                            183   
3                            1                             89   
4                            0                            137   
..                         ...                            ...   
763                         10                            101   
764                          2                            122   
765                          5                            121   
766                          1                            126   
767                          1                             93   

      Diastolic blood pressure   Triceps skin fold thickness  \
0                           72                            35   
1                           66                            29   
2                           64                             0   
3                           66                            23   
4                           40                            35   
..                         ...                           ...   
763                         76                            48   
764                         70                            27   
765                         72                            23   
766                         60                             0   
767                         70                            31   

      2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                        0              33.6                        0.627   
1                        0              26.6                        0.351   
2                        0              23.3                        0.672   
3                       94              28.1                        0.167   
4                      168              43.1                        2.288   
..                     ...               ...                          ...   
763                    180              32.9                        0.171   
764                      0              36.8                        0.340   
765                    112              26.2                        0.245   
766                      0              30.1                        0.349   
767                      0              30.4                        0.315   

      Age (years)  Class variable  
0              50             YES  
1              31              NO  
2              32             YES  
3              21              NO  
4              33             YES  
..            ...             ...  
763            63              NO  
764            27              NO  
765            30              NO  
766            47             YES  
767            23              NO  

[768 rows x 9 columns]

In [3]:
# Check for missing values
df.isna().sum()

 Number of times pregnant        0
 Plasma glucose concentration    0
 Diastolic blood pressure        0
 Triceps skin fold thickness     0
 2-Hour serum insulin            0
 Body mass index                 0
 Diabetes pedigree function      0
 Age (years)                     0
 Class variable                  0
dtype: int64

# LabelEncoding

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [5]:
df[" Class variable"]=le.fit_transform(df[" Class variable"])

In [6]:
x=df.iloc[:,0:8]
x

Number of times pregnant   Plasma glucose concentration  \
0                            6                            148   
1                            1                             85   
2                            8                            183   
3                            1                             89   
4                            0                            137   
..                         ...                            ...   
763                         10                            101   
764                          2                            122   
765                          5                            121   
766                          1                            126   
767                          1                             93   

      Diastolic blood pressure   Triceps skin fold thickness  \
0                           72                            35   
1                           66                            29   
2                           64                             0   
3                           66                            23   
4                           40                            35   
..                         ...                           ...   
763                         76                            48   
764                         70                            27   
765                         72                            23   
766                         60                             0   
767                         70                            31   

      2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                        0              33.6                        0.627   
1                        0              26.6                        0.351   
2                        0              23.3                        0.672   
3                       94              28.1                        0.167   
4                      168              43.1                        2.288   
..                     ...               ...                          ...   
763                    180              32.9                        0.171   
764                      0              36.8                        0.340   
765                    112              26.2                        0.245   
766                      0              30.1                        0.349   
767                      0              30.4                        0.315   

      Age (years)  
0              50  
1              31  
2              32  
3              21  
4              33  
..            ...  
763            63  
764            27  
765            30  
766            47  
767            23  

[768 rows x 8 columns]

In [7]:
y=df[" Class variable"]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name:  Class variable, Length: 768, dtype: int32

# Train Test Split

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=0)

# Model Selection

In [9]:
from sklearn.tree import DecisionTreeRegressor
clf=DecisionTreeRegressor()

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf_random=RandomForestClassifier()

# Fitting  the model

In [11]:
clf.fit(x_train,y_train)

DecisionTreeRegressor()

In [12]:
clf_random.fit(x_train,y_train)

RandomForestClassifier()

# Predicting the model

In [13]:
y_pred=clf.predict(x_test)
y_pred

array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [21]:
y_predt1=clf.predict(x_train)#for test data prediction
y_predt1

array([1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 1.

In [14]:
y_pred_random=clf_random.predict(x_test)
y_pred_random

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Accuracy 

In [15]:
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score 

In [16]:
accuracy_score(y_pred,y_test)

0.7727272727272727

In [17]:
accuracy_score(y_pred_random,y_test)

0.7792207792207793

In [22]:
accuracy_score(y_predt1,y_train)#for train accuracy

1.0

In [24]:
from sklearn import tree
clf=tree.DecisionTreeClassifier(random_state=0)

In [30]:
clf=clf.fit(x,y)

In [34]:
plt.figure(figsize=(200,180))
tree.plot_tree(clf,filled=True)

[Text(5434.27734375, 9435.342857142856, 'X[1] <= 127.5\ngini = 0.454\nsamples = 768\nvalue = [500, 268]'),
 Text(2329.8046875, 8736.42857142857, 'X[7] <= 28.5\ngini = 0.313\nsamples = 485\nvalue = [391, 94]'),
 Text(1231.875, 8037.5142857142855, 'X[5] <= 45.4\ngini = 0.155\nsamples = 271\nvalue = [248, 23]'),
 Text(821.25, 7338.599999999999, 'X[5] <= 30.95\ngini = 0.139\nsamples = 267\nvalue = [247, 20]'),
 Text(270.0, 6639.685714285713, 'X[0] <= 7.5\ngini = 0.026\nsamples = 151\nvalue = [149, 2]'),
 Text(180.0, 5940.771428571428, 'X[6] <= 0.672\ngini = 0.013\nsamples = 150\nvalue = [149, 1]'),
 Text(90.0, 5241.857142857142, 'gini = 0.0\nsamples = 131\nvalue = [131, 0]'),
 Text(270.0, 5241.857142857142, 'X[6] <= 0.686\ngini = 0.1\nsamples = 19\nvalue = [18, 1]'),
 Text(180.0, 4542.942857142856, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(360.0, 4542.942857142856, 'gini = 0.0\nsamples = 18\nvalue = [18, 0]'),
 Text(360.0, 5940.771428571428, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]

In [ ]:
from sklearn import tree
clf=tree.DecisionTreeClassifier(random_state=0)